/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentica profissional ou administrador.
         * @description Retorna tokens JWT Better Auth e informações de sessão.
         */
        post: operations["loginProfessional"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/patient-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia sessão de paciente via PIN de 4 dígitos.
         * @description Valida PIN e retorna cookie `patient_session` HttpOnly.
         */
        post: operations["loginPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova tokens de sessão profissional/admin. */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra sessão atual (profissional/admin ou paciente). */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista profissionais com filtros básicos. */
        get: operations["listProfessionals"];
        put?: never;
        /**
         * Cria ou convida um profissional.
         * @description Disponível apenas para administradores. Usa Idempotency-Key para evitar duplicidade.
         */
        post: operations["inviteProfessional"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professionals/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do profissional autenticado. */
        get: operations["getMyProfessionalProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza dados do próprio perfil profissional. */
        patch: operations["updateMyProfessionalProfile"];
        trace?: never;
    };
    "/professionals/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza a senha do profissional autenticado. */
        patch: operations["updateMyProfessionalPassword"];
        trace?: never;
    };
    "/professionals/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Completa o cadastro do profissional autoatendido.
         * @description Permite que profissionais recém-cadastrados informem dados obrigatórios para acessar o gerenciador.
         */
        post: operations["completeProfessionalOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professionals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha profissional. */
        get: operations["getProfessional"];
        /** Atualiza dados do profissional. */
        put: operations["updateProfessional"];
        post?: never;
        /** Remove profissional. */
        delete: operations["deleteProfessional"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pacientes com filtros. */
        get: operations["listPatients"];
        put?: never;
        /** Cadastra novo paciente. */
        post: operations["createPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca rápida de pacientes. */
        get: operations["searchPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha paciente. */
        get: operations["getPatient"];
        /** Atualiza paciente. */
        put: operations["updatePatient"];
        post?: never;
        /** Arquiva paciente. */
        delete: operations["archivePatient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista contatos do paciente. */
        get: operations["listPatientContacts"];
        put?: never;
        /** Adiciona contato de paciente. */
        post: operations["addPatientContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de estágio/status. */
        get: operations["listPatientStatusHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados do paciente autenticado via app. */
        get: operations["getMyPatientProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista consultas. */
        get: operations["listAppointments"];
        put?: never;
        /** Cria consulta/agendamento. */
        post: operations["createAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha consulta. */
        get: operations["getAppointment"];
        /** Atualiza consulta. */
        put: operations["updateAppointment"];
        post?: never;
        /** Cancela consulta. */
        delete: operations["cancelAppointment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma presença de paciente. */
        post: operations["confirmAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paciente informa que não poderá comparecer. */
        post: operations["declineAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atualiza status de consulta (profissional/admin). */
        post: operations["updateAppointmentStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista intercorrências do paciente. */
        get: operations["listOccurrences"];
        put?: never;
        /** Registra intercorrência para paciente. */
        post: operations["createOccurrence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista alertas com filtros. */
        get: operations["listAlerts"];
        put?: never;
        /** Cria alerta manualmente. */
        post: operations["createAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha alerta. */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza status ou resolução do alerta. */
        patch: operations["updateAlert"];
        trace?: never;
    };
    "/reports/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores de comparecimento. */
        get: operations["getAttendanceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/wait-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tempos de espera entre etapas. */
        get: operations["getWaitTimesReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/adherence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores de adesão ao tratamento. */
        get: operations["getAdherenceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
        "/reports/alerts": {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** Lista de alertas. */
            get: operations["getAlertsReport"];
            put?: never;
            post?: never;
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
    "/reports/adverse-effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Relatório de intercorrências adversas. */
        get: operations["getAdverseEffectsReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{kind}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta relatórios em PDF ou XLSX. */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/appointment-reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agendamento/disparo de lembretes de consulta. */
        post: operations["enqueueAppointmentReminders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Código simbólico do erro. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        PaginationMeta: {
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            statusCounts?: {
                /** Format: int32 */
                total?: number;
                /** Format: int32 */
                active?: number;
                /** Format: int32 */
                inactive?: number;
            };
        };
        User: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            documentId: string;
            specialty?: string;
            phone?: string;
            avatarUrl?: string | null;
            isActive: boolean;
            mustChangePassword: boolean;
            roles: ("admin" | "professional")[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProfessionalCreateInput: {
            name: string;
            /** Format: email */
            email: string;
            /** @description CPF/CRM/CRO conforme papel. */
            documentId: string;
            specialty?: string;
            phone?: string;
            roles: ("admin" | "professional")[];
        };
        ProfessionalUpdateInput: components["schemas"]["ProfessionalCreateInput"];
        ProfessionalProfileUpdateInput: {
            name?: string;
            specialty?: string | null;
            phone?: string | null;
            avatarDataUrl?: string | null;
        };
        ProfessionalOnboardingRequest: {
            fullName: string;
            /** @description CPF do profissional (somente dígitos). */
            documentId: string;
            specialty: string;
            /** @description Telefone de contato com DDD. */
            phone?: string | null;
        };
        ProfessionalOnboardingResponse: {
            /** @enum {string} */
            status: "created" | "updated";
            /** Format: int64 */
            userId: number;
            roles: ("admin" | "professional")[];
        };
        /** @enum {string} */
        PatientStage: "pre_triage" | "in_treatment" | "post_treatment";
        /** @enum {string} */
        PatientStatus: "active" | "inactive" | "at_risk";
        Patient: {
            /** Format: int64 */
            id: number;
            fullName: string;
            cpf: string;
            /** Format: date */
            birthDate?: string | null;
            phone?: string | null;
            emergencyPhone?: string | null;
            tumorType?: string | null;
            clinicalUnit?: string | null;
            stage: components["schemas"]["PatientStage"];
            status: components["schemas"]["PatientStatus"];
            /** Format: uri */
            audioMaterialUrl?: string | null;
            /** Format: int32 */
            pinAttempts?: number;
            /** Format: date-time */
            pinBlockedUntil?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PatientSummary: {
            /** Format: int64 */
            id: number;
            fullName: string;
            cpf: string;
            stage?: components["schemas"]["PatientStage"];
            status: components["schemas"]["PatientStatus"];
        };
        PatientDetail: components["schemas"]["Patient"] & {
            contacts?: components["schemas"]["PatientContact"][];
            occurrences?: components["schemas"]["Occurrence"][];
            alerts?: components["schemas"]["Alert"][];
        };
        PatientCreateInput: {
            fullName: string;
            cpf: string;
            /** Format: date */
            birthDate?: string | null;
            phone?: string | null;
            emergencyPhone?: string | null;
            tumorType?: string | null;
            clinicalUnit?: string | null;
            stage?: components["schemas"]["PatientStage"];
            status?: components["schemas"]["PatientStatus"];
            /** Format: uri */
            audioMaterialUrl?: string | null;
            /** @description PIN de 4 dígitos, será armazenado como hash Argon2. */
            pin: string;
            contacts?: components["schemas"]["PatientContactInput"][];
        };
        PatientUpdateInput: {
            fullName?: string;
            /** Format: date */
            birthDate?: string | null;
            phone?: string | null;
            emergencyPhone?: string | null;
            tumorType?: string | null;
            clinicalUnit?: string | null;
            stage?: components["schemas"]["PatientStage"];
            status?: components["schemas"]["PatientStatus"];
            /** Format: uri */
            audioMaterialUrl?: string | null;
        };
        PatientContact: {
            /** Format: int64 */
            id: number;
            fullName: string;
            relation: string;
            phone: string;
            /** @default false */
            isPrimary: boolean;
        };
        PatientContactInput: {
            fullName: string;
            relation: string;
            phone: string;
            /** @default false */
            isPrimary: boolean;
        };
        PatientStatusHistory: {
            /** Format: int64 */
            id: number;
            stage: components["schemas"]["PatientStage"];
            status: components["schemas"]["PatientStatus"];
            reason?: string | null;
            /** Format: date-time */
            recordedAt: string;
            /** Format: int64 */
            recordedBy?: number | null;
        };
        PatientMobileView: {
            patient?: components["schemas"]["Patient"];
            nextAppointments?: components["schemas"]["Appointment"][];
            audioMaterials?: {
                title?: string;
                /** Format: uri */
                url?: string;
            }[];
        };
        Appointment: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            patientId: number;
            /** Format: int64 */
            professionalId: number;
            /** Format: date-time */
            startsAt: string;
            type: components["schemas"]["AppointmentType"];
            status: components["schemas"]["AppointmentStatus"];
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AppointmentDetail: components["schemas"]["Appointment"] & {
            patient?: components["schemas"]["PatientSummary"];
            professional?: components["schemas"]["User"];
            reminders?: components["schemas"]["AppointmentReminder"][];
        };
        /** @enum {string} */
        AppointmentType: "triage" | "treatment" | "return";
        /** @enum {string} */
        AppointmentStatus: "scheduled" | "confirmed" | "completed" | "no_show" | "canceled";
        AppointmentCreateInput: {
            /** Format: int64 */
            patientId: number;
            /** Format: int64 */
            professionalId: number;
            /** Format: date-time */
            startsAt: string;
            type: components["schemas"]["AppointmentType"];
            notes?: string | null;
        };
        AppointmentUpdateInput: {
            /** Format: date-time */
            startsAt?: string;
            type?: components["schemas"]["AppointmentType"];
            notes?: string;
        };
        AppointmentReminder: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            appointmentId: number;
            channel: components["schemas"]["ReminderChannel"];
            /** Format: date-time */
            scheduledFor: string;
            /** Format: date-time */
            sentAt?: string | null;
            status: components["schemas"]["ReminderStatus"];
            error?: string | null;
        };
        /** @enum {string} */
        ReminderChannel: "whatsapp" | "sms";
        /** @enum {string} */
        ReminderStatus: "queued" | "sent" | "failed";
        Occurrence: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            patientId: number;
            /** Format: int64 */
            professionalId: number;
            kind: string;
            /** Format: int32 */
            intensity: number;
            /** @enum {string} */
            source: "patient" | "professional";
            notes?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OccurrenceCreateInput: {
            /** Format: int64 */
            professionalId: number;
            kind: string;
            /** Format: int32 */
            intensity: number;
            /** @enum {string} */
            source: "patient" | "professional";
            notes?: string | null;
        };
        Alert: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            patientId: number;
            kind: string;
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            details?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
            /** Format: int64 */
            resolvedBy?: number | null;
        };
        /** @enum {string} */
        AlertSeverity: "low" | "medium" | "high";
        /** @enum {string} */
        AlertStatus: "open" | "acknowledged" | "closed";
        AlertCreateInput: {
            /** Format: int64 */
            patientId: number;
            kind: string;
            severity: components["schemas"]["AlertSeverity"];
            details?: string | null;
        };
        AlertUpdateInput: {
            status?: components["schemas"]["AlertStatus"];
            details?: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** Format: int64 */
            resolvedBy?: number;
        };
        AttendanceReport: {
            period?: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
            };
            totals?: {
                scheduled?: number;
                confirmed?: number;
                completed?: number;
                noShow?: number;
                /** Format: float */
                cancellationRate?: number;
            };
        };
        WaitTimesReport: {
            /** Format: float */
            averageDaysToTriage?: number;
            /** Format: float */
            averageDaysToTreatment?: number;
            /** Format: float */
            medianQueueTime?: number;
        };
        AdherenceReport: {
            period?: {
                start?: string;
                end?: string;
            };
            totals?: {
                completedAppointments?: number;
                symptomReportCount?: number;
            };
            patients?: {
                withCompletedAppointments?: number;
                reportingSymptoms?: number;
                engaged?: number;
                /** Format: float */
                engagementRate?: number;
            };
        };
        AlertsReport: {
            period?: {
                start?: string;
                end?: string;
            };
            totals?: {
                status?: {
                    open?: number;
                    acknowledged?: number;
                    closed?: number;
                };
                severity?: {
                    low?: number;
                    medium?: number;
                    high?: number;
                };
            };
            recent?: {
                id?: number;
                patientId?: number;
                kind?: string;
                severity?: "low" | "medium" | "high";
                status?: "open" | "acknowledged" | "closed";
                /** Format: date-time */
                createdAt?: string;
            }[];
        };
        AdverseEffectsReport: {
            topOccurrences?: {
                kind?: string;
                count?: number;
            }[];
            severityBreakdown?: {
                [key: string]: number;
            };
        };
        PaginatedUsers: {
            data: components["schemas"]["User"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedPatients: {
            data: components["schemas"]["PatientSummary"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedAppointments: {
            data: components["schemas"]["Appointment"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginatedAlerts: {
            data: components["schemas"]["Alert"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description Requisição inválida. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Autenticação necessária ou inválida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso não encontrado. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Violação de unicidade ou estado inconsistente. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Erro inesperado. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Número máximo de itens retornados. */
        Limit: number;
        /** @description Deslocamento para paginação baseada em offset. */
        Offset: number;
        /** @description Identificador idempotente por requisição (UUID recomendado). */
        IdempotencyKey: string;
        UserId: number;
        PatientId: number;
        AppointmentId: number;
        AlertId: number;
        /** @description Data inicial do intervalo (inclusive). */
        ReportRangeStart: string;
        /** @description Data final do intervalo (inclusive). */
        ReportRangeEnd: string;
    };
    requestBodies: never;
    headers: {
        /** @description Limite de requisições permitido na janela. */
        "RateLimit-Limit": number;
        /** @description Requisições restantes na janela atual. */
        "RateLimit-Remaining": number;
        /** @description Epoch (segundos) até o reset do limite. */
        "RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginProfessional: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Autenticado com sucesso. */
            200: {
                headers: {
                    "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                    "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                    "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        refreshToken?: string;
                        /**
                         * Format: int32
                         * @description Tempo de expiração em segundos.
                         */
                        expiresIn?: number;
                        user?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    loginPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description CPF do paciente. */
                    cpf: string;
                    /** @description PIN de 4 dígitos. */
                    pin: string;
                };
            };
        };
        responses: {
            /** @description Sessão iniciada; cookie `patient_session` configurado. */
            204: {
                headers: {
                    /** @description Cookie HttpOnly com token de sessão de paciente. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Paciente temporariamente bloqueado após tentativas inválidas. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Token renovado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        refreshToken?: string;
                        /** Format: int32 */
                        expiresIn?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout efetuado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listProfessionals: {
        parameters: {
            query?: {
                /** @description Busca por nome, e-mail ou documento. */
                q?: string;
                /** @description Filtra resultados por status de atividade. */
                status?: "active" | "inactive";
                /** @description Número máximo de itens retornados. */
                limit?: components["parameters"]["Limit"];
                /** @description Deslocamento para paginação baseada em offset. */
                offset?: components["parameters"]["Offset"];
                /** @description Define se a resposta deve incluir contagem agregada por status. */
                includeSummary?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de profissionais. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsers"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    inviteProfessional: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador idempotente por requisição (UUID recomendado). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfessionalCreateInput"];
            };
        };
        responses: {
            /** @description Profissional criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    getMyProfessionalProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil recuperado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    updateMyProfessionalProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfessionalProfileUpdateInput"];
            };
        };
        responses: {
            /** @description Perfil atualizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    updateMyProfessionalPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    newPassword: string;
                    confirmPassword: string;
                };
            };
        };
        responses: {
            /** @description Senha atualizada com sucesso. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    completeProfessionalOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfessionalOnboardingRequest"];
            };
        };
        responses: {
            /** @description Perfil profissional atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalOnboardingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    getProfessional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profissional encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    updateProfessional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfessionalUpdateInput"];
            };
        };
        responses: {
            /** @description Profissional atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    deleteProfessional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profissional removido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    listPatients: {
        parameters: {
            query?: {
                /** @description Busca por nome ou CPF. */
                q?: string;
                status?: components["schemas"]["PatientStatus"];
                stage?: components["schemas"]["PatientStage"];
                /** @description Número máximo de itens retornados. */
                limit?: components["parameters"]["Limit"];
                /** @description Deslocamento para paginação baseada em offset. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de pacientes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPatients"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPatient: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador idempotente por requisição (UUID recomendado). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateInput"];
            };
        };
        responses: {
            /** @description Paciente criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    searchPatients: {
        parameters: {
            query: {
                /** @description Termo de busca (nome ou CPF). */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultados da busca. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paciente encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    updatePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdateInput"];
            };
        };
        responses: {
            /** @description Paciente atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    archivePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paciente arquivado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    listPatientContacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contatos do paciente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientContact"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addPatientContact: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador idempotente por requisição (UUID recomendado). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientContactInput"];
            };
        };
        responses: {
            /** @description Contato criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientContact"];
                };
            };
            400: components["responses"]["BadRequest"];
            default: components["responses"]["Error"];
        };
    };
    listPatientStatusHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico do paciente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientStatusHistory"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyPatientProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil do paciente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientMobileView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    listAppointments: {
        parameters: {
            query?: {
                day?: string;
                patientId?: number;
                professionalId?: number;
                status?: components["schemas"]["AppointmentStatus"];
                /** @description Número máximo de itens retornados. */
                limit?: components["parameters"]["Limit"];
                /** @description Deslocamento para paginação baseada em offset. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de consultas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAppointments"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAppointment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identificador idempotente por requisição (UUID recomendado). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreateInput"];
            };
        };
        responses: {
            /** @description Consulta criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Conflito de horário. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    updateAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentUpdateInput"];
            };
        };
        responses: {
            /** @description Consulta atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    cancelAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consulta cancelada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    confirmAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presença confirmada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    declineAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Ausência registrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateAppointmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AppointmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["AppointmentStatus"];
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Status atualizado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listOccurrences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de intercorrências. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Occurrence"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOccurrence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PatientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrenceCreateInput"];
            };
        };
        responses: {
            /** @description Intercorrência registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Occurrence"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"];
                severity?: components["schemas"]["AlertSeverity"];
                /** @description Número máximo de itens retornados. */
                limit?: components["parameters"]["Limit"];
                /** @description Deslocamento para paginação baseada em offset. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de alertas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlerts"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreateInput"];
            };
        };
        responses: {
            /** @description Alerta criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AlertId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alerta encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    updateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AlertId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdateInput"];
            };
        };
        responses: {
            /** @description Alerta atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    getAttendanceReport: {
        parameters: {
            query?: {
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas de frequência. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWaitTimesReport: {
        parameters: {
            query?: {
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas de tempo de espera. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitTimesReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAdherenceReport: {
        parameters: {
            query?: {
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas de adesão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdherenceReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAlertsReport: {
        parameters: {
            query?: {
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas consolidadas de alertas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAdverseEffectsReport: {
        parameters: {
            query?: {
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estatísticas de efeitos adversos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdverseEffectsReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportReport: {
        parameters: {
            query: {
                format: "pdf" | "xlsx";
                /** @description Data inicial do intervalo (inclusive). */
                start?: components["parameters"]["ReportRangeStart"];
                /** @description Data final do intervalo (inclusive). */
                end?: components["parameters"]["ReportRangeEnd"];
            };
            header?: never;
            path: {
                kind: "attendance" | "wait-times" | "adherence" | "adverse-effects";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo gerado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    enqueueAppointmentReminders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    appointments: {
                        /** Format: int64 */
                        appointmentId: number;
                        channel: components["schemas"]["ReminderChannel"];
                        /** Format: date-time */
                        scheduledFor: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Lembretes enfileirados. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int32 */
                        enqueued?: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
